#!/bin/bash
rm -f .coverage.o
swift test --enable-code-coverage
ld -r -o .coverage.o $(find .build/debug/xenon_view_sdk.build -name '*.o' -print0 | xargs -0 printf '%s ')
xcrun llvm-cov report   --ignore-filename-regex='(.build|Tests)[/\\].*'   -instr-profile "$(swift test --show-codecov-path | xargs dirname)"/default.profdata .coverage.o
