#!/bin/bash
set -eu
cd "$(dirname "$0")"
swift package describe --type json > project.json
.build/checkouts/mockingbird/mockingbird generate --project project.json \
  --output-dir Tests/xenon_view_sdkTests/mocks \
  --testbundle xenon_view_sdkTests \
  --targets xenon_view_sdk